### ISSUE TITLE
ModuleNotFoundError: No module named 'lightning'

### ISSUE THREAD

**Issue by wangxintao2002** [tshu-w/DBCopilot#4]
When I run 
```
 ./scripts/sweep --config configs/sweep_fit_schema_questioning.yaml
``` 
I encounted
 ```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/ubuntu/DBCopilot/src/__init__.py", line 1, in <module>
    from . import callbacks, datamodules, models
  File "/home/ubuntu/DBCopilot/src/callbacks/__init__.py", line 1, in <module>
    from .metric import Metric
  File "/home/ubuntu/DBCopilot/src/callbacks/metric.py", line 5, in <module>
    import lightning.pytorch as pl
ModuleNotFoundError: No module named 'lightning'
```
How to solve this?

**Comment by tshu-w** [comment]
Have you install the dependencies as described? https://github.com/tshu-w/DBCopilot?tab=readme-ov-file#how-to-run

**Comment by tshu-w** [comment]
Close due to no response.
